"""Trims the captures (scripts/finmind/captures/) into the data module the
FinMind diorama imports: src/three/scenes/finmind-captures.js.
Run from the repo root: python scripts/finmind/trim.py"""
import json, re

D = 'scripts/finmind/captures/'
load = lambda f: json.load(open(D + f, encoding='utf8'))
pub = load('fire-published.json')
calc = load('fire-calc.json')
langs = load('fire-languages.json')
miss = load('fire-model-missing.json')['en']
ret = load('retrieval.json')
req = load('fire-request.json')

sid = lambda s: str(s)[:8]
figures = lambda v: int(re.search(r'(\d+) ₹ figure', v['trust']['checks'][1]['detail']).group(1))
out = {
    'request': req,
    'published': {
        'stages': [s for s in pub['stages'] if s['status'] != 'start'],
        'latencyMs': pub['latencyMs'], 'score': pub['trust']['groundedScore'], 'model': pub['model'],
        'citations': pub['citations'], 'successPct': pub['successPct'],
        'checks': [[c['key'], c['label'], c['passed'], c['detail']] for c in pub['trust']['checks']],
    },
    'steps': [[s['group'], s['label'], s['formula'], s['value']] for s in calc['meta']['calculations']],
    'bands': {str(p['age']): [p['p10'], p['p50'], p['p90']] for p in calc['projection'] if p['age'] in (30, 40, 50)},
    'languages': {k: {'line': v['milestones'][0], 'impact': v['fireImpact'], 'figures': figures(v), 'score': v['trust']['groundedScore'],
                      'retried': any(s['status'] == 'retry' for s in v['stages'])} for k, v in langs.items()},
    'retry': next(s['detail'] for s in langs['en']['stages'] if s['status'] == 'retry'),
    'template': {'impact': miss['fireImpact'], 'milestones': miss['milestones'][:3]},
    'retrieval': [{
        'id': q['id'], 'question': q['question'], 'taxYear': q['taxYear'], 'expanded': q['expanded'],
        'exactTerm': q['exactTerm'], 'keywordUsed': q['keywordUsed'],
        'vector': [[sid(v['id']), v['score'], v['title'], v['authority'], v['section']] for v in q['vector']],
        'keyword': [[sid(k['id']), k['bm25'], k['title'], k['authority'], k['section']] for k in q['keyword']],
        'fused': [[sid(f['id']), f['rrf'], f['title'], f['authority'], f['section'], f['fromVector'], f['fromKeyword'], f['text']] for f in q['fused']],
        'app': [a['score'] for a in q['app']],
    } for q in ret],
}
js = ('/**\n * What the FinMind product itself returned (scripts/finmind/README.md says\n'
      ' * how each capture was made). Generated by scripts/finmind/trim.py: do not edit.\n */\n'
      'export default ' + json.dumps(out, ensure_ascii=False, separators=(',', ':')) + ';\n')
open('src/three/scenes/finmind-captures.js', 'w', encoding='utf8').write(js)
print(len(js), 'bytes')
